### ISSUE TITLE
Extend given content object rather than creating a new one

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-content-model#23]
https://github.com/Financial-Times/n-content-model/blob/master/main.js#L7

I think it may actually be cheaper to extend the `content` object at this point rather than create a new object. The reason being that it's already in memory and because it's referenced elsewhere it will stay in memory, therefore creating a new 'lighter' object may actually be a little heavier.

I think this also has the advantage of not needing to maintain 'pass-through' properties that do not get modified.

**Comment by andygnewman** [comment]
👍  Good idea, sounds like a major version.

**Comment by andygnewman** [comment]
Had some further thoughts on this.

You're right that there's an issue with having to explicitly pass-through non-modified properties.

A simple solution could be that within n-content-model we only do the new and modified properties into a new object and then the implementation in the calling application would use an Object.assign rather than a replacement to merge the new properties into the existing ones.

**Comment by andygnewman** [comment]
Suggested way forward on this;

- create a new repo, eg. `n-content-decorator` based on this repo
- focus it only on transforming properties, not passing through untouched ones
- have two usage options;
    1. decorate by mutating the original item
    2. pass back a new object containing only the new or altered properties which the calling application can assign onto the original item
- in this way the calling application has to be explicitly aware of opaque mutation
- then deprecate this module

**Comment by leggsimon** [comment]
I mean, it seems like unnecessary work to create a new repo and deprecate this rather than just change the use of this repo?
